services:
  opensearch:
    image: opensearchproject/opensearch:3.1.0
    container_name: os
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ljwtyn88.
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - os-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://localhost:9200 | grep -q "cluster_name"
  
  dashboards:
    image: opensearchproject/opensearch-dashboards:3.1.0
    container_name: os-dash
    environment:
      - OPENSEARCH_HOSTS=http://os:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy

  logstash:
    build:
      context: ./logstash
    image: docker.elastic.co/logstash/logstash:7.17.13
    container_name: os-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logs:/usr/share/logstash/logs
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - LS_JAVA_OPTS=-Xms8g -Xmx8g

volumes:
  os-data:
